import { useEffect, useRef, useState } from "react";
import type { ChangeEvent } from "react";

import { ArtifactFrame } from "./ArtifactFrame";

const WORDS = [
	"Let me",
	"check",
	"on",
	"that —",
	"I",
	"don't",
	"see",
	"anything",
	"at",
	"8",
	"tonight.",
];
// The unretractable claim starts at "I": everything from here contradicts
// the result the sub-agent is about to return.
const WRONG_FROM = 4;

const SPEECH_START = 300;
const SPEECH_MS = 260;
const GEN_START = 140;
const GEN_MS = 70;
const BUFFER_MS = 520;
const RESUME_GEN_DELAY = 130;
const HOLD_TAIL = 500;
const LOOP_HOLD = 1200;
const ARRIVAL_MIN = 200;
const ARRIVAL_MAX = 2600;
const ARRIVAL_DEFAULT = 900;

const speakAt = (index: number) => SPEECH_START + index * SPEECH_MS;
const genAt = (index: number) => GEN_START + index * GEN_MS;

// Once "see" enters the committed audio buffer it will be spoken no matter
// what, so the splice can no longer help.
const FAIL_AFTER = speakAt(6) - BUFFER_MS;

type ModelChipState = "ghost" | "generated" | "dropped" | "resume";
type HeardChipState = "ghost" | "queued" | "spoken" | "wrong";

interface Chip {
	text: string;
	model: ModelChipState;
	heard: HeardChipState;
	seamBefore: boolean;
}

function isFailed(arrival: number): boolean {
	return arrival >= FAIL_AFTER;
}

function lastKeptIndex(arrival: number): number {
	let last = 0;
	for (let i = 0; i < WORDS.length; i++) {
		if (speakAt(i) < arrival + BUFFER_MS) last = i;
	}
	return last;
}

/**
 * A steered continuation has to follow whatever is already committed. The
 * later the result lands, the more of the wrong sentence the resume has to
 * repair around — exactly the behavior interrupted-continuation training
 * exists to teach.
 */
function resumeWords(arrival: number): string[] {
	const last = lastKeptIndex(arrival);
	if (last <= 1) return ["—", "8", "is", "open."];
	if (last === 2) return ["that —", "8", "is", "open."];
	if (last === 3) return ["8", "is", "open."];
	if (last === 4) return ["see", "it —", "8", "is", "open."];
	return ["— wait,", "8", "is", "open."];
}

function resumeGenAt(arrival: number, index: number): number {
	return arrival + RESUME_GEN_DELAY + index * GEN_MS;
}

function resumeSpeakAt(arrival: number, index: number): number {
	return speakAt(lastKeptIndex(arrival)) + SPEECH_MS * (index + 1);
}

function endFor(arrival: number): number {
	if (isFailed(arrival)) {
		return speakAt(WORDS.length - 1) + SPEECH_MS + HOLD_TAIL;
	}
	const resume = resumeWords(arrival);
	return resumeSpeakAt(arrival, resume.length - 1) + SPEECH_MS + HOLD_TAIL;
}

function chipsFor(arrival: number, clock: number): Chip[] {
	const failed = isFailed(arrival);
	const chips: Chip[] = WORDS.map((text, i) => {
		if (failed) {
			const spoken = clock >= speakAt(i);
			const wrong = i >= WRONG_FROM && spoken && clock >= arrival;
			return {
				text,
				model: clock >= genAt(i) ? "generated" : "ghost",
				heard: wrong
					? "wrong"
					: spoken
						? "spoken"
						: clock >= genAt(i)
							? "queued"
							: "ghost",
				seamBefore: false,
			};
		}
		const kept = speakAt(i) < arrival + BUFFER_MS;
		if (kept) {
			return {
				text,
				model: clock >= genAt(i) ? "generated" : "ghost",
				heard:
					clock >= speakAt(i)
						? "spoken"
						: clock >= genAt(i)
							? "queued"
							: "ghost",
				seamBefore: false,
			};
		}
		// Generation halts at arrival: words not generated by then never exist.
		const generated = genAt(i) <= arrival && clock >= genAt(i);
		return {
			text,
			model: generated ? (clock >= arrival ? "dropped" : "generated") : "ghost",
			heard: generated && clock < arrival ? "queued" : "ghost",
			seamBefore: false,
		};
	});

	if (failed) return chips;

	const spliced = clock >= arrival;
	const resumeChips: Chip[] = resumeWords(arrival).map((text, j) => ({
		text,
		model: clock >= resumeGenAt(arrival, j) ? "resume" : "ghost",
		heard:
			clock >= resumeSpeakAt(arrival, j)
				? "spoken"
				: clock >= resumeGenAt(arrival, j)
					? "queued"
					: "ghost",
		seamBefore: j === 0 && spliced,
	}));
	return [...chips, ...resumeChips];
}

function modelChipClass(state: ModelChipState): string {
	switch (state) {
		case "ghost":
			return "token-cell token-ghost";
		case "generated":
			return "token-cell token-generated";
		case "dropped":
			return "token-cell token-dropped";
		case "resume":
			return "token-cell token-resume";
		default: {
			const exhaustive: never = state;
			return exhaustive;
		}
	}
}

function heardChipClass(state: HeardChipState): string {
	switch (state) {
		case "ghost":
			return "token-cell token-ghost";
		case "queued":
			return "token-cell token-queued";
		case "spoken":
			return "token-cell token-spoken";
		case "wrong":
			return "token-cell token-wrong";
		default: {
			const exhaustive: never = state;
			return exhaustive;
		}
	}
}

interface TokenSpliceProps {
	figure?: number;
}

/**
 * Figure: a live simulation of mid-utterance splicing. The model row fills
 * fast (generation), the caller row fills at exactly 1× (audio playback), and
 * the gap between them is the padding a splice can use. Drag the arrival time
 * to see what can still change — and when it is too late.
 */
export default function TokenSplice({ figure }: TokenSpliceProps) {
	const rootRef = useRef<HTMLDivElement>(null);
	const [arrival, setArrival] = useState(ARRIVAL_DEFAULT);
	const [clock, setClock] = useState(() => endFor(ARRIVAL_DEFAULT));
	const [motionOk, setMotionOk] = useState(false);
	const [inView, setInView] = useState(false);
	const [dragging, setDragging] = useState(false);

	useEffect(() => {
		if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
		setMotionOk(true);
		setClock(0);
		const root = rootRef.current;
		if (!root) return;
		const observer = new IntersectionObserver(
			(entries) => setInView(entries.some((entry) => entry.isIntersecting)),
			{ threshold: 0.3 },
		);
		observer.observe(root);
		return () => observer.disconnect();
	}, []);

	const running = motionOk && inView && !dragging;

	useEffect(() => {
		if (!running) return;
		const end = endFor(arrival);
		let start = performance.now();
		let frame = requestAnimationFrame(function step(now: number) {
			let elapsed = now - start;
			if (elapsed >= end + LOOP_HOLD) {
				start = now;
				elapsed = 0;
			}
			setClock(Math.min(elapsed, end));
			frame = requestAnimationFrame(step);
		});
		return () => cancelAnimationFrame(frame);
	}, [running, arrival]);

	const onArrivalChange = (event: ChangeEvent<HTMLInputElement>) => {
		const value = Number(event.target.value);
		setArrival(value);
		// While dragging (or without motion) show the outcome for this arrival;
		// the loop effect replays from zero on release.
		if (!motionOk || dragging) setClock(endFor(value));
	};

	const displayClock = dragging || !motionOk ? endFor(arrival) : clock;
	const chips = chipsFor(arrival, displayClock);
	const failed = isFailed(arrival);

	return (
		<ArtifactFrame
			figure={figure}
			title="You can only change what you haven't said"
			caption={
				failed
					? "By the time the result showed up, “I don't see” was already headed for the speaker. Nothing we splice after that can unsay it."
					: "We generate way faster than we speak, so there's always a tail the caller hasn't heard yet. When the result lands, we drop that tail and keep generating with the result in context."
			}
		>
			<div className="splice-sim" ref={rootRef}>
				<label className="splice-control">
					<span className="splice-control-row">
						<span>
							result arrives at <strong>{arrival} ms</strong>
						</span>
						<span className="splice-clock">
							t = {Math.round(displayClock)} ms
						</span>
					</span>
					<input
						type="range"
						min={ARRIVAL_MIN}
						max={ARRIVAL_MAX}
						step={20}
						value={arrival}
						onChange={onArrivalChange}
						onPointerDown={() => setDragging(true)}
						onPointerUp={() => {
							setDragging(false);
							if (motionOk) setClock(0);
						}}
					/>
				</label>
				<div className="splice-track">
					<div className="splice-track-label">
						model
						<span>generates ahead</span>
					</div>
					<div className="splice-chips">
						{chips.map((chip, index) => (
							<span
								className="splice-chip-slot"
								key={`m-${chip.text}-${index}`}
							>
								{chip.seamBefore && (
									<span className="splice-seam" aria-hidden="true" />
								)}
								<span className={modelChipClass(chip.model)}>{chip.text}</span>
							</span>
						))}
					</div>
				</div>
				<div className="splice-track">
					<div className="splice-track-label">
						caller hears
						<span>audio at 1×</span>
					</div>
					<div className="splice-chips">
						{chips.map((chip, index) => (
							<span
								className="splice-chip-slot"
								key={`h-${chip.text}-${index}`}
							>
								{chip.seamBefore && (
									<span
										className="splice-seam splice-seam-quiet"
										aria-hidden="true"
									/>
								)}
								<span className={heardChipClass(chip.heard)}>{chip.text}</span>
							</span>
						))}
					</div>
				</div>
				<div className="token-legend">
					<LegendSwatch className="token-spoken" label="spoken" />
					<LegendSwatch className="token-queued" label="queued audio" />
					<LegendSwatch className="token-generated" label="generated ahead" />
					<LegendSwatch className="token-dropped" label="dropped at splice" />
					{failed ? (
						<LegendSwatch className="token-wrong" label="wrong fact heard" />
					) : (
						<LegendSwatch className="token-resume" label="spliced resume" />
					)}
				</div>
			</div>
		</ArtifactFrame>
	);
}

function LegendSwatch({
	className,
	label,
}: {
	className: string;
	label: string;
}) {
	return (
		<span className="token-legend-item">
			<span className={`token-cell ${className} token-cell-swatch`}>·</span>
			{label}
		</span>
	);
}
